height = 'tall'
weight = 'average'
hair = 'eatin'
eyes = 'lots'
build = 'of'
first_name = 'Holly'
last_name = 'Frannz'
full_name = 'Holly Frannz'
gender = 'female'
female = True
male = False
p_nom = 'she'
p_gen = 'her'
p_acc = 'her'
